namespace IqTest.Application.Reference;

/// <summary>A country a participant can pick when joining the board.</summary>
/// <param name="Code">ISO 3166-1 alpha-2, upper case.</param>
/// <param name="Name">English short name.</param>
public sealed record Country(string Code, string Name)
{
    /// <summary>
    /// The flag emoji for this country, built from the regional indicator
    /// letters of its code, so no image assets are needed.
    /// </summary>
    public string Flag => string.Concat(Code.Select(c => char.ConvertFromUtf32(0x1F1E6 + (c - 'A'))));
}

/// <summary>
/// The ISO 3166-1 alpha-2 list, generated from the iso-codes package. A
/// closed list rather than free text keeps the country column groupable.
/// </summary>
public static class Countries
{
    private static readonly IReadOnlyList<Country> AllCountries =
    [
        new("AF", "Afghanistan"),
        new("AL", "Albania"),
        new("DZ", "Algeria"),
        new("AS", "American Samoa"),
        new("AD", "Andorra"),
        new("AO", "Angola"),
        new("AI", "Anguilla"),
        new("AQ", "Antarctica"),
        new("AG", "Antigua and Barbuda"),
        new("AR", "Argentina"),
        new("AM", "Armenia"),
        new("AW", "Aruba"),
        new("AU", "Australia"),
        new("AT", "Austria"),
        new("AZ", "Azerbaijan"),
        new("BS", "Bahamas"),
        new("BH", "Bahrain"),
        new("BD", "Bangladesh"),
        new("BB", "Barbados"),
        new("BY", "Belarus"),
        new("BE", "Belgium"),
        new("BZ", "Belize"),
        new("BJ", "Benin"),
        new("BM", "Bermuda"),
        new("BT", "Bhutan"),
        new("BO", "Bolivia"),
        new("BQ", "Bonaire, Sint Eustatius and Saba"),
        new("BA", "Bosnia and Herzegovina"),
        new("BW", "Botswana"),
        new("BV", "Bouvet Island"),
        new("BR", "Brazil"),
        new("IO", "British Indian Ocean Territory"),
        new("BN", "Brunei Darussalam"),
        new("BG", "Bulgaria"),
        new("BF", "Burkina Faso"),
        new("BI", "Burundi"),
        new("CV", "Cabo Verde"),
        new("KH", "Cambodia"),
        new("CM", "Cameroon"),
        new("CA", "Canada"),
        new("KY", "Cayman Islands"),
        new("CF", "Central African Republic"),
        new("TD", "Chad"),
        new("CL", "Chile"),
        new("CN", "China"),
        new("CX", "Christmas Island"),
        new("CC", "Cocos (Keeling) Islands"),
        new("CO", "Colombia"),
        new("KM", "Comoros"),
        new("CG", "Congo"),
        new("CD", "Congo, The Democratic Republic of the"),
        new("CK", "Cook Islands"),
        new("CR", "Costa Rica"),
        new("HR", "Croatia"),
        new("CU", "Cuba"),
        new("CW", "Curaçao"),
        new("CY", "Cyprus"),
        new("CZ", "Czechia"),
        new("CI", "Côte d'Ivoire"),
        new("DK", "Denmark"),
        new("DJ", "Djibouti"),
        new("DM", "Dominica"),
        new("DO", "Dominican Republic"),
        new("EC", "Ecuador"),
        new("EG", "Egypt"),
        new("SV", "El Salvador"),
        new("GQ", "Equatorial Guinea"),
        new("ER", "Eritrea"),
        new("EE", "Estonia"),
        new("SZ", "Eswatini"),
        new("ET", "Ethiopia"),
        new("FK", "Falkland Islands (Malvinas)"),
        new("FO", "Faroe Islands"),
        new("FJ", "Fiji"),
        new("FI", "Finland"),
        new("FR", "France"),
        new("GF", "French Guiana"),
        new("PF", "French Polynesia"),
        new("TF", "French Southern Territories"),
        new("GA", "Gabon"),
        new("GM", "Gambia"),
        new("GE", "Georgia"),
        new("DE", "Germany"),
        new("GH", "Ghana"),
        new("GI", "Gibraltar"),
        new("GR", "Greece"),
        new("GL", "Greenland"),
        new("GD", "Grenada"),
        new("GP", "Guadeloupe"),
        new("GU", "Guam"),
        new("GT", "Guatemala"),
        new("GG", "Guernsey"),
        new("GN", "Guinea"),
        new("GW", "Guinea-Bissau"),
        new("GY", "Guyana"),
        new("HT", "Haiti"),
        new("HM", "Heard Island and McDonald Islands"),
        new("VA", "Holy See (Vatican City State)"),
        new("HN", "Honduras"),
        new("HK", "Hong Kong"),
        new("HU", "Hungary"),
        new("IS", "Iceland"),
        new("IN", "India"),
        new("ID", "Indonesia"),
        new("IR", "Iran"),
        new("IQ", "Iraq"),
        new("IE", "Ireland"),
        new("IM", "Isle of Man"),
        new("IL", "Israel"),
        new("IT", "Italy"),
        new("JM", "Jamaica"),
        new("JP", "Japan"),
        new("JE", "Jersey"),
        new("JO", "Jordan"),
        new("KZ", "Kazakhstan"),
        new("KE", "Kenya"),
        new("KI", "Kiribati"),
        new("KW", "Kuwait"),
        new("KG", "Kyrgyzstan"),
        new("LA", "Laos"),
        new("LV", "Latvia"),
        new("LB", "Lebanon"),
        new("LS", "Lesotho"),
        new("LR", "Liberia"),
        new("LY", "Libya"),
        new("LI", "Liechtenstein"),
        new("LT", "Lithuania"),
        new("LU", "Luxembourg"),
        new("MO", "Macao"),
        new("MG", "Madagascar"),
        new("MW", "Malawi"),
        new("MY", "Malaysia"),
        new("MV", "Maldives"),
        new("ML", "Mali"),
        new("MT", "Malta"),
        new("MH", "Marshall Islands"),
        new("MQ", "Martinique"),
        new("MR", "Mauritania"),
        new("MU", "Mauritius"),
        new("YT", "Mayotte"),
        new("MX", "Mexico"),
        new("FM", "Micronesia, Federated States of"),
        new("MD", "Moldova"),
        new("MC", "Monaco"),
        new("MN", "Mongolia"),
        new("ME", "Montenegro"),
        new("MS", "Montserrat"),
        new("MA", "Morocco"),
        new("MZ", "Mozambique"),
        new("MM", "Myanmar"),
        new("NA", "Namibia"),
        new("NR", "Nauru"),
        new("NP", "Nepal"),
        new("NL", "Netherlands"),
        new("NC", "New Caledonia"),
        new("NZ", "New Zealand"),
        new("NI", "Nicaragua"),
        new("NE", "Niger"),
        new("NG", "Nigeria"),
        new("NU", "Niue"),
        new("NF", "Norfolk Island"),
        new("KP", "North Korea"),
        new("MK", "North Macedonia"),
        new("MP", "Northern Mariana Islands"),
        new("NO", "Norway"),
        new("OM", "Oman"),
        new("PK", "Pakistan"),
        new("PW", "Palau"),
        new("PS", "Palestine, State of"),
        new("PA", "Panama"),
        new("PG", "Papua New Guinea"),
        new("PY", "Paraguay"),
        new("PE", "Peru"),
        new("PH", "Philippines"),
        new("PN", "Pitcairn"),
        new("PL", "Poland"),
        new("PT", "Portugal"),
        new("PR", "Puerto Rico"),
        new("QA", "Qatar"),
        new("RO", "Romania"),
        new("RU", "Russian Federation"),
        new("RW", "Rwanda"),
        new("RE", "Réunion"),
        new("BL", "Saint Barthélemy"),
        new("SH", "Saint Helena, Ascension and Tristan da Cunha"),
        new("KN", "Saint Kitts and Nevis"),
        new("LC", "Saint Lucia"),
        new("MF", "Saint Martin (French part)"),
        new("PM", "Saint Pierre and Miquelon"),
        new("VC", "Saint Vincent and the Grenadines"),
        new("WS", "Samoa"),
        new("SM", "San Marino"),
        new("ST", "Sao Tome and Principe"),
        new("SA", "Saudi Arabia"),
        new("SN", "Senegal"),
        new("RS", "Serbia"),
        new("SC", "Seychelles"),
        new("SL", "Sierra Leone"),
        new("SG", "Singapore"),
        new("SX", "Sint Maarten (Dutch part)"),
        new("SK", "Slovakia"),
        new("SI", "Slovenia"),
        new("SB", "Solomon Islands"),
        new("SO", "Somalia"),
        new("ZA", "South Africa"),
        new("GS", "South Georgia and the South Sandwich Islands"),
        new("KR", "South Korea"),
        new("SS", "South Sudan"),
        new("ES", "Spain"),
        new("LK", "Sri Lanka"),
        new("SD", "Sudan"),
        new("SR", "Suriname"),
        new("SJ", "Svalbard and Jan Mayen"),
        new("SE", "Sweden"),
        new("CH", "Switzerland"),
        new("SY", "Syria"),
        new("TW", "Taiwan"),
        new("TJ", "Tajikistan"),
        new("TZ", "Tanzania"),
        new("TH", "Thailand"),
        new("TL", "Timor-Leste"),
        new("TG", "Togo"),
        new("TK", "Tokelau"),
        new("TO", "Tonga"),
        new("TT", "Trinidad and Tobago"),
        new("TN", "Tunisia"),
        new("TM", "Turkmenistan"),
        new("TC", "Turks and Caicos Islands"),
        new("TV", "Tuvalu"),
        new("TR", "Türkiye"),
        new("UG", "Uganda"),
        new("UA", "Ukraine"),
        new("AE", "United Arab Emirates"),
        new("GB", "United Kingdom"),
        new("US", "United States"),
        new("UM", "United States Minor Outlying Islands"),
        new("UY", "Uruguay"),
        new("UZ", "Uzbekistan"),
        new("VU", "Vanuatu"),
        new("VE", "Venezuela"),
        new("VN", "Vietnam"),
        new("VG", "Virgin Islands, British"),
        new("VI", "Virgin Islands, U.S."),
        new("WF", "Wallis and Futuna"),
        new("EH", "Western Sahara"),
        new("YE", "Yemen"),
        new("ZM", "Zambia"),
        new("ZW", "Zimbabwe"),
        new("AX", "Åland Islands"),
    ];

    public static IReadOnlyList<Country> All => AllCountries;

    private static readonly IReadOnlyDictionary<string, Country> ByCodeLookup =
        AllCountries.ToDictionary(c => c.Code, StringComparer.OrdinalIgnoreCase);

    public static bool IsKnown(string? code) =>
        !string.IsNullOrWhiteSpace(code) && ByCodeLookup.ContainsKey(code.Trim());

    public static Country? Find(string? code) =>
        !string.IsNullOrWhiteSpace(code) && ByCodeLookup.TryGetValue(code.Trim(), out var country) ? country : null;

    /// <summary>Falls back to the raw code, so an unknown value still renders.</summary>
    public static string NameOf(string? code) => Find(code)?.Name ?? (code ?? "Unknown");

    public static string FlagOf(string? code) => Find(code)?.Flag ?? "\U0001F3F3";
}
